-- Idempotent database-owned V1 catalog seed.
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.income','Income','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.income.salary','Salary','system','category.income','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.income.bonus','Bonus','system','category.income','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.income.investment','Investment Income','system','category.income','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.income.refund','Refund','system','category.income','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.income.other','Other Income','system','category.income','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.food','Food & Dining','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.food.restaurants','Restaurants','system','category.food','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.food.groceries','Groceries','system','category.food','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.food.coffee','Coffee & Drinks','system','category.food','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.food.delivery','Delivery & Takeout','system','category.food','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.transportation','Transportation','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.transportation.fuel','Fuel','system','category.transportation','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.transportation.parking','Parking','system','category.transportation','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.housing','Housing','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.housing.rent_mortgage','Rent & Mortgage','system','category.housing','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.housing.utilities','Utilities','system','category.housing','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.housing.maintenance','Home Maintenance','system','category.housing','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.shopping','Shopping','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.shopping.clothing','Clothing','system','category.shopping','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.shopping.electronics','Electronics','system','category.shopping','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.shopping.household','Household','system','category.shopping','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.health','Health','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.health.medical','Medical','system','category.health','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.health.pharmacy','Pharmacy','system','category.health','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.health.fitness','Fitness','system','category.health','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.entertainment','Entertainment','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.entertainment.events','Events','system','category.entertainment','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.travel','Travel','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.travel.airfare','Airfare','system','category.travel','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.travel.hotel','Hotels','system','category.travel','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.travel.local','Local Transportation','system','category.travel','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.education','Education','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.personal','Personal Care','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.gifts','Gifts & Donations','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.insurance','Insurance','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.taxes','Taxes','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.fees','Fees & Charges','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.transfer','Transfer','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.uncategorized','Uncategorized','system',NULL,'active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.other','Other','system',NULL,'active');
INSERT OR IGNORE INTO tags (id,name,status) VALUES ('tag.business','Business','active');
INSERT OR IGNORE INTO tags (id,name,status) VALUES ('tag.personal','Personal','active');
INSERT OR IGNORE INTO tags (id,name,status) VALUES ('tag.reimbursable','Reimbursable','active');
INSERT OR IGNORE INTO tags (id,name,status) VALUES ('tag.tax_related','Tax Related','active');
INSERT OR IGNORE INTO tags (id,name,status) VALUES ('tag.travel','Travel','active');
INSERT OR IGNORE INTO tags (id,name,status) VALUES ('tag.recurring','Recurring','active');
INSERT OR IGNORE INTO tags (id,name,status) VALUES ('tag.subscription','Subscription','active');

INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.transportation.public','Public Transit','system','category.transportation','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.transportation.rideshare','Taxi & Rideshare','system','category.transportation','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.transportation.maintenance','Vehicle Maintenance','system','category.transportation','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.entertainment.streaming','Streaming & Subscriptions','system','category.entertainment','active');
INSERT OR IGNORE INTO categories (id,name,origin,parent_id,status) VALUES ('category.entertainment.events','Events','system','category.entertainment','active');

-- Built-in merchant defaults are suggestions only; users may classify them differently.
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.safeway','Safeway','safeway','category.food','category.food.groceries',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.costco','Costco','costco','category.food','category.food.groceries',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.walmart','Walmart','walmart','category.shopping',NULL,1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.amazon','Amazon','amazon','category.shopping',NULL,1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.starbucks','Starbucks','starbucks','category.food','category.food.coffee',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.target','Target','target','category.shopping',NULL,1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.whole_foods','Whole Foods','whole foods','category.food','category.food.groceries',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.trader_joes','Trader Joe''s','trader joe s','category.food','category.food.groceries',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.walgreens','Walgreens','walgreens','category.health','category.health.pharmacy',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.cvs','CVS','cvs','category.health','category.health.pharmacy',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.home_depot','Home Depot','home depot','category.housing','category.housing.maintenance',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.shell','Shell','shell','category.transportation','category.transportation.fuel',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.chevron','Chevron','chevron','category.transportation','category.transportation.fuel',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.uber','Uber','uber','category.transportation','category.transportation.rideshare',1,'active');
INSERT OR IGNORE INTO merchants (id,name,normalized_name,default_category_id,default_subcategory_id,is_built_in,status) VALUES ('merchant.lyft','Lyft','lyft','category.transportation','category.transportation.rideshare',1,'active');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income','en','Income');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.salary','en','Salary');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.bonus','en','Bonus');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.investment','en','Investment Income');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.refund','en','Refund');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.other','en','Other Income');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food','en','Food & Dining');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food.restaurants','en','Restaurants');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food.groceries','en','Groceries');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food.coffee','en','Coffee & Drinks');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food.delivery','en','Delivery & Takeout');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation','en','Transportation');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.fuel','en','Fuel');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.public','en','Public Transit');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.rideshare','en','Taxi & Rideshare');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.parking','en','Parking');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.maintenance','en','Vehicle Maintenance');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.housing','en','Housing');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.housing.rent_mortgage','en','Rent & Mortgage');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.housing.utilities','en','Utilities');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.housing.maintenance','en','Home Maintenance');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.shopping','en','Shopping');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.shopping.clothing','en','Clothing');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.shopping.electronics','en','Electronics');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.shopping.household','en','Household');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.health','en','Health');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.health.medical','en','Medical');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.health.pharmacy','en','Pharmacy');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.health.fitness','en','Fitness');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.entertainment','en','Entertainment');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.entertainment.streaming','en','Streaming & Subscriptions');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.entertainment.events','en','Events');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.travel','en','Travel');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.travel.airfare','en','Airfare');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.travel.hotel','en','Hotels');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.travel.local','en','Local Transportation');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.education','en','Education');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.personal','en','Personal Care');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.gifts','en','Gifts & Donations');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.insurance','en','Insurance');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.taxes','en','Taxes');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.fees','en','Fees & Charges');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transfer','en','Transfer');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.uncategorized','en','Uncategorized');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.other','en','Other');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.business','en','Business');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.personal','en','Personal');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.reimbursable','en','Reimbursable');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.tax_related','en','Tax Related');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.travel','en','Travel');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.recurring','en','Recurring');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.subscription','en','Subscription');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income','zh-Hans','收入');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.salary','zh-Hans','工资');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.bonus','zh-Hans','奖金');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.investment','zh-Hans','投资收入');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.refund','zh-Hans','退款');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.income.other','zh-Hans','其他收入');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food','zh-Hans','餐饮');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food.restaurants','zh-Hans','餐厅');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food.groceries','zh-Hans','食品杂货');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food.coffee','zh-Hans','咖啡与饮品');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.food.delivery','zh-Hans','外卖与外带');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation','zh-Hans','交通');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.fuel','zh-Hans','燃油');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.public','zh-Hans','公共交通');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.rideshare','zh-Hans','出租车与网约车');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.parking','zh-Hans','停车');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transportation.maintenance','zh-Hans','车辆维护');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.housing','zh-Hans','住房');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.housing.rent_mortgage','zh-Hans','房租与房贷');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.housing.utilities','zh-Hans','水电燃气');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.housing.maintenance','zh-Hans','房屋维护');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.shopping','zh-Hans','购物');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.shopping.clothing','zh-Hans','服装');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.shopping.electronics','zh-Hans','电子产品');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.shopping.household','zh-Hans','家居用品');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.health','zh-Hans','医疗健康');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.health.medical','zh-Hans','医疗');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.health.pharmacy','zh-Hans','药品');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.health.fitness','zh-Hans','健身');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.entertainment','zh-Hans','娱乐');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.entertainment.streaming','zh-Hans','流媒体与订阅');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.entertainment.events','zh-Hans','活动');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.travel','zh-Hans','旅行');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.travel.airfare','zh-Hans','机票');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.travel.hotel','zh-Hans','酒店');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.travel.local','zh-Hans','当地交通');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.education','zh-Hans','教育');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.personal','zh-Hans','个人护理');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.gifts','zh-Hans','礼物与捐赠');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.insurance','zh-Hans','保险');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.taxes','zh-Hans','税费');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.fees','zh-Hans','手续费与费用');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.transfer','zh-Hans','转账');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.uncategorized','zh-Hans','未分类');
INSERT OR IGNORE INTO category_translations (category_id,locale,label) VALUES ('category.other','zh-Hans','其他');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.business','zh-Hans','商务');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.personal','zh-Hans','个人');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.reimbursable','zh-Hans','可报销');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.tax_related','zh-Hans','税务相关');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.travel','zh-Hans','旅行');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.recurring','zh-Hans','定期');
INSERT OR IGNORE INTO tag_translations (tag_id,locale,label) VALUES ('tag.subscription','zh-Hans','订阅');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('transaction.direction.expense','expense','transaction.direction','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('transaction.direction.expense','en','Expense');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('transaction.direction.expense','zh-Hans','支出');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('transaction.direction.income','income','transaction.direction','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('transaction.direction.income','en','Income');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('transaction.direction.income','zh-Hans','收入');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('transaction.direction.transfer','transfer','transaction.direction','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('transaction.direction.transfer','en','Transfer');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('transaction.direction.transfer','zh-Hans','转账');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('payment_source.type.credit_card','credit_card','payment_source.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.credit_card','en','Credit Card');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.credit_card','zh-Hans','信用卡');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('payment_source.type.debit_card','debit_card','payment_source.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.debit_card','en','Debit Card');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.debit_card','zh-Hans','借记卡');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('payment_source.type.bank_account','bank_account','payment_source.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.bank_account','en','Bank Account');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.bank_account','zh-Hans','银行账户');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('payment_source.type.cash','cash','payment_source.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.cash','en','Cash');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.cash','zh-Hans','现金');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('payment_source.type.other','other','payment_source.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.other','en','Other');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('payment_source.type.other','zh-Hans','其他');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('card_network.visa','visa','card_network','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.visa','en','Visa');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.visa','zh-Hans','Visa');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('card_network.mastercard','mastercard','card_network','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.mastercard','en','Mastercard');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.mastercard','zh-Hans','Mastercard');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('card_network.discover','discover','card_network','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.discover','en','Discover');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.discover','zh-Hans','Discover');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('card_network.unionpay','unionpay','card_network','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.unionpay','en','UnionPay');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.unionpay','zh-Hans','银联');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('card_network.jcb','jcb','card_network','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.jcb','en','JCB');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.jcb','zh-Hans','JCB');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('card_network.other','other','card_network','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.other','en','Other');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.other','zh-Hans','其他');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('card_network.unknown','unknown','card_network','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.unknown','en','Unknown');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('card_network.unknown','zh-Hans','未知');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('evidence.type.receipt','receipt','evidence.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.receipt','en','Receipt');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.receipt','zh-Hans','收据');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('evidence.type.statement','statement','evidence.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.statement','en','Statement');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.statement','zh-Hans','账单');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('evidence.type.import','import','evidence.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.import','en','Imported Record');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.import','zh-Hans','导入记录');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('evidence.type.manual','manual','evidence.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.manual','en','Manual Entry');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.manual','zh-Hans','手动录入');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('evidence.type.other','other','evidence.type','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.other','en','Other Evidence');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('evidence.type.other','zh-Hans','其他凭证');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('review.status.none','none','review.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('review.status.none','en','No Review Needed');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('review.status.none','zh-Hans','无需审核');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('review.status.needs_review','needs_review','review.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('review.status.needs_review','en','Needs Review');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('review.status.needs_review','zh-Hans','需要审核');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('review.status.in_review','in_review','review.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('review.status.in_review','en','In Review');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('review.status.in_review','zh-Hans','审核中');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('review.status.resolved','resolved','review.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('review.status.resolved','en','Resolved');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('review.status.resolved','zh-Hans','已解决');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('reconciliation.status.unmatched','unmatched','reconciliation.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.unmatched','en','Unmatched');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.unmatched','zh-Hans','未匹配');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('reconciliation.status.candidate','candidate','reconciliation.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.candidate','en','Candidate');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.candidate','zh-Hans','候选匹配');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('reconciliation.status.confirmed','confirmed','reconciliation.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.confirmed','en','Confirmed');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.confirmed','zh-Hans','已确认');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('reconciliation.status.rejected','rejected','reconciliation.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.rejected','en','Rejected');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.rejected','zh-Hans','已拒绝');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('reconciliation.status.superseded','superseded','reconciliation.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.superseded','en','Superseded');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('reconciliation.status.superseded','zh-Hans','已取代');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('analysis.finding.status.active','active','analysis.finding.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.status.active','en','Active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.status.active','zh-Hans','有效');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('analysis.finding.status.dismissed','dismissed','analysis.finding.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.status.dismissed','en','Dismissed');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.status.dismissed','zh-Hans','已忽略');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('analysis.finding.status.superseded','superseded','analysis.finding.status','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.status.superseded','en','Superseded');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.status.superseded','zh-Hans','已取代');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('analysis.finding.missing_data','missing_data','analysis.finding','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.missing_data','en','Missing Data');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.missing_data','zh-Hans','数据缺失');
INSERT OR IGNORE INTO reference_data (id,code,type,origin,status) VALUES ('analysis.finding.data_quality','data_quality','analysis.finding','system','active');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.data_quality','en','Data Quality');
INSERT OR IGNORE INTO reference_data_translations (reference_data_id,locale,label) VALUES ('analysis.finding.data_quality','zh-Hans','数据质量');
