import 'package:butlerly/design_system/tokens/butlerly_category_colors.dart';

/// Persistent visual identity for a category.
///
/// Application theme controls surfaces and text. Category identity controls
/// the category glyph and fixed color. User-facing labels remain in the
/// localization/master-data layer and are never used as lookup keys.
enum ButlerlyCategoryIdentityKind { builtIn, custom }

final class ButlerlyCategoryIdentity {
  const ButlerlyCategoryIdentity._({
    required this.kind,
    required this.categoryId,
    required this.assetName,
    required this.categoryColorId,
    required this.localizationKey,
  });

  final ButlerlyCategoryIdentityKind kind;
  final String categoryId;
  final String assetName;
  final ButlerlyCategoryColorId categoryColorId;
  final String localizationKey;

  String get assetPath => 'assets/icons/categories/$assetName.svg';

  /// Resolves a system category. Unknown IDs return null and are not custom.
  static ButlerlyCategoryIdentity? forBuiltInId(String categoryId) =>
      _builtIns[categoryId];

  /// Creates the identity for a persisted user category.
  ///
  /// The color must come from the persisted custom-category record. The
  /// current Category domain entity has no color field yet, so callers must
  /// supply that value when the persistence model gains this capability.
  static ButlerlyCategoryIdentity custom({
    required String categoryId,
    required ButlerlyCategoryColorId categoryColorId,
  }) => ButlerlyCategoryIdentity._(
    kind: ButlerlyCategoryIdentityKind.custom,
    categoryId: categoryId,
    assetName: 'custom',
    categoryColorId: categoryColorId,
    localizationKey: 'category',
  );

  /// The keys are the authoritative built-in category IDs represented here.
  static Iterable<String> get builtInCategoryIds => _builtIns.keys;

  static const _builtIns = <String, ButlerlyCategoryIdentity>{
    'category.income': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income',
      assetName: 'income',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.income',
    ),
    'category.income.salary': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.salary',
      assetName: 'investments',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.income.salary',
    ),
    'category.income.bonus': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.bonus',
      assetName: 'investments',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.income.bonus',
    ),
    'category.income.investment': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.investment',
      assetName: 'investments',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.income.investment',
    ),
    'category.income.interest': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.interest',
      assetName: 'investments',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.income.interest',
    ),
    'category.income.dividends': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.dividends',
      assetName: 'investments',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.income.dividends',
    ),
    'category.income.rental': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.rental',
      assetName: 'income',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.income.rental',
    ),
    'category.income.reimbursement': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.reimbursement',
      assetName: 'refunds',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.income.reimbursement',
    ),
    'category.income.tax_refund': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.tax_refund',
      assetName: 'refunds',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.income.tax_refund',
    ),
    'category.income.refund': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.refund',
      assetName: 'refunds',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.income.refund',
    ),
    'category.income.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.income.other',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.income.other',
    ),
    'category.food': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.food',
      assetName: 'food_dining',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.food',
    ),
    'category.food.restaurants': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.food.restaurants',
      assetName: 'food_dining',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.food.restaurants',
    ),
    'category.food.groceries': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.food.groceries',
      assetName: 'groceries',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.food.groceries',
    ),
    'category.food.coffee': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.food.coffee',
      assetName: 'coffee',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.food.coffee',
    ),
    'category.food.delivery': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.food.delivery',
      assetName: 'food_dining',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.food.delivery',
    ),
    'category.transportation': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transportation',
      assetName: 'transport',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.transportation',
    ),
    'category.transportation.fuel': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transportation.fuel',
      assetName: 'fuel',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.transportation.fuel',
    ),
    'category.transportation.public': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transportation.public',
      assetName: 'transport',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.transportation.public',
    ),
    'category.transportation.rideshare': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transportation.rideshare',
      assetName: 'car',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.transportation.rideshare',
    ),
    'category.transportation.parking': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transportation.parking',
      assetName: 'parking_tolls',
      categoryColorId: ButlerlyCategoryColorId.purple,
      localizationKey: 'category.transportation.parking',
    ),
    'category.transportation.maintenance': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transportation.maintenance',
      assetName: 'car',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.transportation.maintenance',
    ),
    'category.housing': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.housing',
      assetName: 'home',
      categoryColorId: ButlerlyCategoryColorId.purple,
      localizationKey: 'category.housing',
    ),
    'category.housing.rent_mortgage': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.housing.rent_mortgage',
      assetName: 'home',
      categoryColorId: ButlerlyCategoryColorId.purple,
      localizationKey: 'category.housing.rent_mortgage',
    ),
    'category.housing.utilities': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.housing.utilities',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.housing.utilities',
    ),
    'category.housing.maintenance': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.housing.maintenance',
      assetName: 'home_services',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.housing.maintenance',
    ),
    'category.housing.landscaping': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.housing.landscaping',
      assetName: 'home_services',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.housing.landscaping',
    ),
    'category.utilities': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.utilities',
    ),
    'category.utilities.electricity': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities.electricity',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.utilities.electricity',
    ),
    'category.utilities.gas': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities.gas',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.utilities.gas',
    ),
    'category.utilities.water_sewer': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities.water_sewer',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.utilities.water_sewer',
    ),
    'category.utilities.trash_recycling': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities.trash_recycling',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.utilities.trash_recycling',
    ),
    'category.utilities.internet': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities.internet',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.utilities.internet',
    ),
    'category.utilities.mobile_phone': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities.mobile_phone',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.utilities.mobile_phone',
    ),
    'category.utilities.cable_tv': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities.cable_tv',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.purple,
      localizationKey: 'category.utilities.cable_tv',
    ),
    'category.utilities.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.utilities.other',
      assetName: 'utilities',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.utilities.other',
    ),
    'category.shopping': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.shopping',
      assetName: 'shopping',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.shopping',
    ),
    'category.shopping.clothing': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.shopping.clothing',
      assetName: 'shopping',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.shopping.clothing',
    ),
    'category.shopping.electronics': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.shopping.electronics',
      assetName: 'shopping',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.shopping.electronics',
    ),
    'category.shopping.household': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.shopping.household',
      assetName: 'home_supplies',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.shopping.household',
    ),
    'category.shopping.general': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.shopping.general',
      assetName: 'shopping',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.shopping.general',
    ),
    'category.household': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.household',
      assetName: 'home_supplies',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.household',
    ),
    'category.household.supplies': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.household.supplies',
      assetName: 'home_supplies',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.household.supplies',
    ),
    'category.household.cleaning': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.household.cleaning',
      assetName: 'home_supplies',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.household.cleaning',
    ),
    'category.health': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.health',
      assetName: 'health_fitness',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.health',
    ),
    'category.health.medical': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.health.medical',
      assetName: 'medical',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.health.medical',
    ),
    'category.health.pharmacy': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.health.pharmacy',
      assetName: 'medical',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.health.pharmacy',
    ),
    'category.health.hospital': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.health.hospital',
      assetName: 'medical',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.health.hospital',
    ),
    'category.health.dental': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.health.dental',
      assetName: 'medical',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.health.dental',
    ),
    'category.health.vision': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.health.vision',
      assetName: 'medical',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.health.vision',
    ),
    'category.health.mental': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.health.mental',
      assetName: 'health_fitness',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.health.mental',
    ),
    'category.health.fitness': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.health.fitness',
      assetName: 'health_fitness',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.health.fitness',
    ),
    'category.entertainment': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.entertainment',
      assetName: 'entertainment',
      categoryColorId: ButlerlyCategoryColorId.purple,
      localizationKey: 'category.entertainment',
    ),
    'category.entertainment.streaming': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.entertainment.streaming',
      assetName: 'subscriptions',
      categoryColorId: ButlerlyCategoryColorId.purple,
      localizationKey: 'category.entertainment.streaming',
    ),
    'category.entertainment.events': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.entertainment.events',
      assetName: 'movies',
      categoryColorId: ButlerlyCategoryColorId.purple,
      localizationKey: 'category.entertainment.events',
    ),
    'category.digital_services': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.digital_services',
      assetName: 'subscriptions',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.digital_services',
    ),
    'category.digital_services.cloud_storage': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.digital_services.cloud_storage',
      assetName: 'subscriptions',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.digital_services.cloud_storage',
    ),
    'category.digital_services.software_subscription': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.digital_services.software_subscription',
      assetName: 'subscriptions',
      categoryColorId: ButlerlyCategoryColorId.purple,
      localizationKey: 'category.digital_services.software_subscription',
    ),
    'category.digital_services.productivity': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.digital_services.productivity',
      assetName: 'subscriptions',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.digital_services.productivity',
    ),
    'category.digital_services.online_services': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.digital_services.online_services',
      assetName: 'subscriptions',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.digital_services.online_services',
    ),
    'category.digital_services.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.digital_services.other',
      assetName: 'subscriptions',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.digital_services.other',
    ),
    'category.travel': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.travel',
      assetName: 'travel',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.travel',
    ),
    'category.travel.airfare': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.travel.airfare',
      assetName: 'travel',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.travel.airfare',
    ),
    'category.travel.hotel': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.travel.hotel',
      assetName: 'accommodation',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.travel.hotel',
    ),
    'category.travel.local': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.travel.local',
      assetName: 'transport',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.travel.local',
    ),
    'category.travel.car_rental': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.travel.car_rental',
      assetName: 'car',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.travel.car_rental',
    ),
    'category.education': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.education',
      assetName: 'education',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.education',
    ),
    'category.education.tuition_fees': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.education.tuition_fees',
      assetName: 'education',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.education.tuition_fees',
    ),
    'category.education.books_supplies': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.education.books_supplies',
      assetName: 'education',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.education.books_supplies',
    ),
    'category.education.training_courses': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.education.training_courses',
      assetName: 'education',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.education.training_courses',
    ),
    'category.personal': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.personal',
      assetName: 'personal_care',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.personal',
    ),
    'category.personal.oral': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.personal.oral',
      assetName: 'personal_care',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.personal.oral',
    ),
    'category.personal.hair': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.personal.hair',
      assetName: 'personal_care',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.personal.hair',
    ),
    'category.personal.bath_body': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.personal.bath_body',
      assetName: 'personal_care',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.personal.bath_body',
    ),
    'category.gifts': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.gifts',
      assetName: 'gifts_donations',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.gifts',
    ),
    'category.gifts.personal': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.gifts.personal',
      assetName: 'gifts_donations',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.gifts.personal',
    ),
    'category.gifts.family_support': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.gifts.family_support',
      assetName: 'gifts_donations',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.gifts.family_support',
    ),
    'category.gifts.charity': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.gifts.charity',
      assetName: 'gifts_donations',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.gifts.charity',
    ),
    'category.gifts.religious': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.gifts.religious',
      assetName: 'gifts_donations',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.gifts.religious',
    ),
    'category.gifts.crowdfunding': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.gifts.crowdfunding',
      assetName: 'gifts_donations',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.gifts.crowdfunding',
    ),
    'category.gifts.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.gifts.other',
      assetName: 'gifts_donations',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.gifts.other',
    ),
    'category.insurance': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.insurance',
      assetName: 'insurance',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.insurance',
    ),
    'category.insurance.auto': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.insurance.auto',
      assetName: 'insurance',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.insurance.auto',
    ),
    'category.insurance.homeowners': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.insurance.homeowners',
      assetName: 'insurance',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.insurance.homeowners',
    ),
    'category.insurance.health': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.insurance.health',
      assetName: 'insurance',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.insurance.health',
    ),
    'category.insurance.life': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.insurance.life',
      assetName: 'insurance',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.insurance.life',
    ),
    'category.insurance.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.insurance.other',
      assetName: 'insurance',
      categoryColorId: ButlerlyCategoryColorId.green,
      localizationKey: 'category.insurance.other',
    ),
    'category.taxes': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.taxes',
      assetName: 'taxes',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.taxes',
    ),
    'category.taxes.income': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.taxes.income',
      assetName: 'taxes',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.taxes.income',
    ),
    'category.taxes.property': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.taxes.property',
      assetName: 'taxes',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.taxes.property',
    ),
    'category.taxes.sales_use': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.taxes.sales_use',
      assetName: 'taxes',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.taxes.sales_use',
    ),
    'category.taxes.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.taxes.other',
      assetName: 'taxes',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.taxes.other',
    ),
    'category.fees': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.fees',
    ),
    'category.fees.bank': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees.bank',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.fees.bank',
    ),
    'category.fees.credit_card': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees.credit_card',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.fees.credit_card',
    ),
    'category.fees.atm': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees.atm',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.fees.atm',
    ),
    'category.fees.late_penalty': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees.late_penalty',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.coral,
      localizationKey: 'category.fees.late_penalty',
    ),
    'category.fees.foreign_transaction': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees.foreign_transaction',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.fees.foreign_transaction',
    ),
    'category.fees.transfer_wire': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees.transfer_wire',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.fees.transfer_wire',
    ),
    'category.fees.account_service': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees.account_service',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.fees.account_service',
    ),
    'category.fees.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.fees.other',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.fees.other',
    ),
    'category.professional_services': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.professional_services',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.professional_services',
    ),
    'category.professional_services.tax_preparation': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.professional_services.tax_preparation',
      assetName: 'taxes',
      categoryColorId: ButlerlyCategoryColorId.gold,
      localizationKey: 'category.professional_services.tax_preparation',
    ),
    'category.professional_services.accounting': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.professional_services.accounting',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.professional_services.accounting',
    ),
    'category.professional_services.legal': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.professional_services.legal',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.professional_services.legal',
    ),
    'category.professional_services.consulting': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.professional_services.consulting',
      assetName: 'financial_fees',
      categoryColorId: ButlerlyCategoryColorId.orange,
      localizationKey: 'category.professional_services.consulting',
    ),
    'category.transfer': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transfer',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.transfer',
    ),
    'category.transfer.own_accounts': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transfer.own_accounts',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.transfer.own_accounts',
    ),
    'category.transfer.credit_card_payment': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transfer.credit_card_payment',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.transfer.credit_card_payment',
    ),
    'category.transfer.brokerage': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transfer.brokerage',
      assetName: 'investments',
      categoryColorId: ButlerlyCategoryColorId.blue,
      localizationKey: 'category.transfer.brokerage',
    ),
    'category.transfer.savings': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transfer.savings',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.teal,
      localizationKey: 'category.transfer.savings',
    ),
    'category.transfer.cash': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transfer.cash',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.transfer.cash',
    ),
    'category.transfer.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.transfer.other',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.transfer.other',
    ),
    'category.uncategorized': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.uncategorized',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.uncategorized',
    ),
    'category.other': ButlerlyCategoryIdentity._(
      kind: ButlerlyCategoryIdentityKind.builtIn,
      categoryId: 'category.other',
      assetName: 'other',
      categoryColorId: ButlerlyCategoryColorId.slate,
      localizationKey: 'category.other',
    ),
  };
}
